name: Publish .NET library to NuGet and GitHub Packages
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      NUGET_API_KEY:
        required: true
  pull_request:
  merge_group:

permissions:
  packages: write

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“‘ Checkout
        uses: actions/checkout@v4
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 9
      - name: Get version from tag
        id: version
        run: echo RELEASE_VERSION=${GITHUB_REF#refs/tags/v} >> $GITHUB_OUTPUT
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ steps.version.outputs.RELEASE_VERSION }}
      - name: Push to NuGet
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      - name: Add GitHub Packages as NuGet Source
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      - name: Push to GitHub Packages
        run: dotnet nuget push **/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
