name: GitOps Lint

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitops-lint:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‘ Checkout
        uses: actions/checkout@v4
      - name: âš™ï¸ Install KSail
        run: |
          curl -L -o ksail https://github.com/devantler-tech/ksail/releases/download/latest/ksail-linux-arm64
          chmod +x ksail
          sudo mv ksail /usr/local/bin/ksail
      - name: ğŸ§¹ Lint GitOps cluster configuration
        run: |
          ksail lint
